services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metriplate_container
    ports:
      - '8080:8080'
    networks:
      - metriplate_net

    environment:
      - SPRING_PROFILES_ACTIVE=dev
    env_file:
      - .env