services:
  metriplate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metriplate_container
    ports:
      - '8080:8080'
    networks:
      - metriplate_net

    environment:
      - SPRING_PROFILES_ACTIVE=dev
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: metriplate
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql
    networks:
      - metriplate_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgAdmin:
    image: 'dpage/pgadmin4'
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - metriplate_net


volumes:
  pg-data:

networks:
  metriplate_net:
