spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/metriplate

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.0-flash
            temperature: 0.5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info

