spring:
  application:
    name: MetriPlate

  profiles:
    active: ${SPRING_ACTIVE_PROFILE}

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  ai:
    model:
      chat: google-genai
    google:
      genai:
        api-key: ${GEMINI_API_KEY}




  jackson:
    mapper:
      accept-case-insensitive-enums: true